### PR TITLE
Modified mock date class to extend Date

### LINKED ISSUE #6: Mock Date class is not extensible
The mock date class is returning a `Date` instance [in the constructor](https://github.com/hustcc/jest-date-mock/blob/master/src/mockDate.js#L12) which breaks extensibility (as an instance of `Date` is returned instead of the one of the class being used to call `new`).

As this is replacing the global `Date` object, any class extending `Date` would be broken.

### PR DESCRIPTION
**Pull request by rubennorte**
The mock class now extends the native Date object in a way that can be further extended by any other class.

It uses the same technique used by Babel to extend native built-ins. Ideally, this library should use Babel 7 and the "env" preset configured for Node 4 (which keeps classes and so extending built-ins is easier and better performant).

Fixes #6.

### CODE REVIEW

File: lib/mockDate.js [hunk 1]
```diff
@@ -40,4 +33,7 @@ var mockDateClass = exports.mockDateClass = function mockDateClass(D) {
   };
 
   return MD;
-};
\ No newline at end of file
+}; /**
```
Comment (rubennorte) [inline lib/mockDate.js]: Babel does this now that it doesn't need the helpers :S

**Comment by prymitive** [comment]
I can confirm that `1.0.5-beta.1` works for me, should I expect `1.0.5` soon?
